!=================================================================================================================
 module CA2G_StateSpecs
 use mpas_kind_types,only: RKIND
 public
 save

!this module is the state variable specification file for carbon parameters. it is the same as CA2G_StateSpecs.rc
!in the GOCART-2G directory ./GOCART-2G/ESMF/GOCART2G_GridComp/CA2G_GridComp.

!schema_version: 2.0.0
!component: CA


 type CA2G_State

!category: IMPORT
 real(kind=RKIND),dimension(:,:),allocatable  :: FROCEAN          ! fraction_of_ocean (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: FRACI            ! ice_covered_fraction_of_tile (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: LWI              ! land-ocean-ice_mask (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: TROPP            ! tropopause_pressure_based_on_blended_estimate (Pa)
 real(kind=RKIND),dimension(:,:),allocatable  :: U10M             ! 10-meter_eastward_wind (m s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: V10M             ! 10-meter_northward_wind (m s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: USTAR            ! surface_velocity_scale (m s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: FRLAKE           ! fraction_of_lake (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: AREA             ! agrid_cell_area (m^2)
 real(kind=RKIND),dimension(:,:),allocatable  :: ZPBL             ! planetary_boundary_layer_height (m)
 real(kind=RKIND),dimension(:,:),allocatable  :: SH               ! sensible_heat_flux_from_turbulence (W m-2)
 real(kind=RKIND),dimension(:,:),allocatable  :: Z0H              ! surface_roughness_for_heat (m)
 real(kind=RKIND),dimension(:,:),allocatable  :: CN_PRCP          ! surface_conv._rain_flux_needed_by_land (kg/m^2/s)
 real(kind=RKIND),dimension(:,:),allocatable  :: NCN_PRCP         ! non-convective precipitation (kg/m^2/s)
!.................................................................................................................
 real(kind=RKIND),dimension(:,:,:),allocatable:: AIRDENS          ! moist_air_density (kg m-3)
 real(kind=RKIND),dimension(:,:,:),allocatable:: DELP             ! pressure_thickness (Pa)
 real(kind=RKIND),dimension(:,:,:),allocatable:: T                ! air_temperature (K)
 real(kind=RKIND),dimension(:,:,:),allocatable:: RH2              ! Rel_Hum_after_moist (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ZLE              ! geopotential_height (m)
 real(kind=RKIND),dimension(:,:,:),allocatable:: PLE              ! air_pressure (Pa)
 real(kind=RKIND),dimension(:,:,:),allocatable:: PFL_LSAN         ! 3D_flux_of_liquid_nonconvective_precipitation (kg/m2/s)
 real(kind=RKIND),dimension(:,:,:),allocatable:: PFI_LSAN         ! 3D_flux_of_ice_nonconvective_precipitation (kg/m2/s)
 real(kind=RKIND),dimension(:,:,:),allocatable:: U                ! eastward_wind (m s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: V                ! northward_wind (m s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: OC_AIRCRAFT      ! aircraft emissions (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: BC_AIRCRAFT      ! aircraft emissions (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: BRC_AIRCRAFT     ! aircraft emissions (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: pSOA_ANTHRO_VOC  ! SOA from Anthropogenic and biomass burning VOC (kg m-3 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: pSOA_BIOB_VOC    ! SOA from Anthropogenic and biomass burning VOC (kg m-3 s-1)
!.................................................................................................................
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_BIOMASS       ! biomass burning emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_ISOPRENE      ! source species (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_MTPA          ! source species (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_MTPO          ! source species (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_LIMO          ! source species (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_BIOFUEL       ! biofuel emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_ANTEOC1       ! anthropogenic BF emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_ANTEOC2       ! anthropogenic FF emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_SHIP          ! ship emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_AVIATION_LTO  ! Landing/Take-off aircraft emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_AVIATION_CDS  ! Climb/Descent aircraft emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: OC_AVIATION_CRS  ! Cruise aircraft source species (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_BIOMASS       ! biomass burning emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_BIOFUEL       ! biofuel emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_ANTEBC1       ! anthropogenic BF emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_ANTEBC2       ! anthropogenic FF emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_SHIP          ! ship emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_AVIATION_LTO  ! Landing/Take-off aircraft emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_AVIATION_CDS  ! Climb/Descent aircraft emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BC_AVIATION_CRS  ! Cruise aircraft source species (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_BIOMASS      ! biomass burning emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_TERPENE      ! terpene emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_BIOFUEL      ! biofuel emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_ANTEBRC1     ! anthropogenic BF emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_ANTEBRC2     ! anthropogenic FF emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_SHIP         ! ship emisisons (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_AVIATION_LTO ! Landing/Take-off aircraft emissions (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_AVIATION_CDS ! Climb/Descent aircraft emissions(-)
 real(kind=RKIND),dimension(:,:),allocatable  :: BRC_AVIATION_CRS ! Cruise aircraft source species (-)

!category: EXPORT
 real(kind=RKIND),dimension(:,:,:),allocatable  :: bcMASS        ! Black carbon aerosol Mass Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:,:),allocatable  :: bcCONC        ! Black carbon aerosol Mass Concentration (kg m-3)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcEXTCOEF     ! Black carbon aerosol Extinction Coefficient (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcEXTCOEFRH20 ! Black carbon aerosol Extinction Coefficient - Fixed RH=20% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcEXTCOEFRH80 ! Black carbon aerosol Extinction Coefficient - Fixed RH=80% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcSCACOEF     ! Black carbon aerosol Scattering Coefficient (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcSCACOEFRH20 ! Black carbon aerosol Scattering Coefficient - Fixed RH=20% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcSCACOEFRH80 ! Black carbon aerosol Scattering Coefficient - Fixed RH=80% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: bcBCKCOEF     ! Black carbon aerosol Backscatter Coefficient (m-1 sr-1)
 real(kind=RKIND),dimension(:,:,:),allocatable  :: brMASS        ! Brown carbon aerosol Mass Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:,:),allocatable  :: brCONC        ! Brown carbon aerosol Mass Concentration (kg m-3)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brEXTCOEF     ! Brown carbon aerosol Extinction Coefficient (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brEXTCOEFRH20 ! Brown carbon aerosol Extinction Coefficient - Fixed RH=20% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brEXTCOEFRH80 ! Brown carbon aerosol Extinction Coefficient - Fixed RH=80% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brSCACOEF     ! Brown carbon aerosol Scattering Coefficient (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brSCACOEFRH20 ! Brown carbon aerosol Scattering Coefficient - Fixed RH=20% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brSCACOEFRH80 ! Brown carbon aerosol Scattering Coefficient - Fixed RH=80% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: brBCKCOEF     ! Brown carbon aerosol Backscatter Coefficient (m-1 sr-1)
 real(kind=RKIND),dimension(:,:,:),allocatable  :: ocMASS        ! Organic carbon aerosol Mass Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:,:),allocatable  :: ocCONC        ! Organic carbon aerosol Mass Concentration (kg m-3)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocEXTCOEF     ! Organic carbon aerosol Extinction Coefficient (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocEXTCOEFRH20 ! Organic carbon aerosol Extinction Coefficient - Fixed RH=20% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocEXTCOEFRH80 ! Organic carbon aerosol Extinction Coefficient - Fixed RH=80% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocSCACOEF     ! Organic carbon aerosol Scattering Coefficient (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocSCACOEFRH20 ! Organic carbon aerosol Scattering Coefficient - Fixed RH=20% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocSCACOEFRH80 ! Organic carbon aerosol Scattering Coefficient - Fixed RH=80% (m-1)
 real(kind=RKIND),dimension(:,:,:,:),allocatable:: ocBCKCOEF     ! Organic carbon aerosol Backscatter Coefficient (m-1 sr-1)
!.................................................................................................................
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcEM            ! Black carbon aerosol Emission (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcSD            ! Black carbon aerosol Sedimentation (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcDP            ! Black carbon aerosol Dry Deposition (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcWT            ! Black carbon aerosol Wet Deposition (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcSV            ! Black carbon aerosol Convective Scavenging (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcEMAN          ! Black carbon aerosol Anthropogenic Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcEMBB          ! Black carbon aerosol Biomass Burning Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcEMBF          ! Black carbon aerosol Biofuel Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcEMBG          ! Black carbon aerosol Biogenic Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcHYPHIL        ! Black carbon aerosol Hydrophobic to Hydrophilic (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcPSOA          ! Black carbon aerosol SOA Production (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcSMASS         ! Black carbon aerosol Surface Mass Concentration (kg m-3)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcCMASS         ! Black carbon aerosol Column Mass Density (kg m-2)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcEXTTAU        ! Black carbon aerosol Extinction AOT (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcSTEXTTAU      ! Black carbon aerosol Extinction AOT Stratosphere (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcSCATAU        ! Black carbon aerosol Scattering AOT (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: bcSTSCATAU      ! Black carbon aerosol Scattering AOT Stratosphere (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcANGSTR        ! Black carbon aerosol Angstrom parameter [470-870 nm] (-)!
 real(kind=RKIND),dimension(:,:),allocatable  :: bcFLUXU         ! Black carbon aerosol column u-wind mass flux (kg m-1 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcFLUXV         ! Black carbon aerosol column v-wind mass flux (kg m-1 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcAERIDX        ! Black carbon aerosol TOMS UV Aerosol Index (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brEM            ! Brown carbon aerosol Emission (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brSD            ! Brown carbon aerosol Sedimentation (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brDP            ! Brown carbon aerosol Dry Deposition (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brWT            ! Brown carbon aerosol Wet Deposition (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brSV            ! Brown carbon aerosol Convective Scavenging (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brEMAN          ! Brown carbon aerosol Anthropogenic Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brEMBB          ! Brown carbon aerosol Biomass Burning Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brEMBF          ! Brown carbon aerosol Biofuel Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brEMBG          ! Brown carbon aerosol Biogenic Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brHYPHIL        ! Brown carbon aerosol Hydrophobic to Hydrophilic (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brPSOA          ! Brown carbon aerosol SOA Production (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brSMASS         ! Brown carbon aerosol Surface Mass Concentration (kg m-3)
 real(kind=RKIND),dimension(:,:),allocatable  :: brCMASS         ! Brown carbon aerosol Column Mass Density (kg m-2)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brEXTTAU        ! Brown carbon aerosol Extinction AOT (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brSTEXTTAU      ! Brown carbon aerosol Extinction AOT Stratosphere (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brSCATAU        ! Brown carbon aerosol Scattering AOT (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: brSTSCATAU      ! Brown carbon aerosol Scattering AOT Stratosphere (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: brANGSTR        ! Brown carbon aerosol Angstrom parameter [470-870 nm] (-)!
 real(kind=RKIND),dimension(:,:),allocatable  :: brFLUXU         ! Brown carbon aerosol column u-wind mass flux (kg m-1 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brFLUXV         ! Brown carbon aerosol column v-wind mass flux (kg m-1 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brAERIDX        ! Brown carbon aerosol TOMS UV Aerosol Index (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocEM            ! Organic carbon aerosol Emission (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocSD            ! Organic carbon aerosol Sedimentation (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocDP            ! Organic carbon aerosol Dry Deposition (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocWT            ! Organic carbon aerosol Wet Deposition (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocSV            ! Organic carbon aerosol Convective Scavenging (Bin %d) (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocEMAN          ! Organic carbon aerosol Anthropogenic Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocEMBB          ! Organic carbon aerosol Biomass Burning Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocEMBF          ! Organic carbon aerosol Biofuel Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocEMBG          ! Organic carbon aerosol Biogenic Emissions (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocHYPHIL        ! Organic carbon aerosol Hydrophobic to Hydrophilic (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocPSOA          ! Organic carbon aerosol SOA Production (kg m-2 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocSMASS         ! Organic carbon aerosol Surface Mass Concentration (kg m-3)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocCMASS         ! Organic carbon aerosol Column Mass Density (kg m-2)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocEXTTAU        ! Organic carbon aerosol Extinction AOT (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocSTEXTTAU      ! Organic carbon aerosol Extinction AOT Stratosphere (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocSCATAU        ! Organic carbon aerosol Scattering AOT (-)
 real(kind=RKIND),dimension(:,:,:),allocatable:: ocSTSCATAU      ! Organic carbon aerosol Scattering AOT Stratosphere (-)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocANGSTR        ! Organic carbon aerosol Angstrom parameter [470-870 nm] (-)!
 real(kind=RKIND),dimension(:,:),allocatable  :: ocFLUXU         ! Organic carbon aerosol column u-wind mass flux (kg m-1 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocFLUXV         ! Organic carbon aerosol column v-wind mass flux (kg m-1 s-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocAERIDX        ! Organic carbon aerosol TOMS UV Aerosol Index (-)

!category: INTERNAL
 real(kind=RKIND),dimension(:,:),allocatable  :: bcphobic        ! Hydrophobic black aerosol Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: bcphilic        ! Hydrophilic black aerosol Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brphobic        ! Hydrophobic brown aerosol Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: brphilic        ! Hydrophilic brown aerosol Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocphobic        ! Hydrophobic organic aerosol Mixing Ratio (kg kg-1)
 real(kind=RKIND),dimension(:,:),allocatable  :: ocphilic        ! Hydrophilic organic aerosol Mixing Ratio (kg kg-1)

 end type CA2G_State

!=================================================================================================================
 end module CA2G_StateSpecs
!=================================================================================================================
